// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaolnncirgayfnufhcuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlhb2xubmNpcmdheWZudWZoY3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzQ5NjcsImV4cCI6MjA2MDgxMDk2N30.Ueql5xkC4Vjd4XQEHZa1MRUjc3TRC4Eu5rDDiRB0YS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);